required = [
#  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/stretchr/testify"
]

#[[constraint]]
#  name = "github.com/golang/mock"
#  version = "1.1.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

#[[constraint]]
#  name = "github.com/golang/protobuf"
#  version = "v1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
